name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build-native-component:
    strategy:
      matrix:
        build-type: [Debug, Release]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Cache webOS NDK
      id: cache-ndk
      uses: actions/cache@v3
      with:
        path: ${{github.workspace}}/temp/webos-sdk-x86_64-armv7a-neon-toolchain-1.0.g.sh
        key: ${{ runner.os }}-ndk

    - name: Download webOS NDK
      if: steps.cache-ndk.outputs.cache-hit != 'true'
      run: wget -q https://github.com/webosbrew/meta-lg-webos-ndk/releases/download/1.0.g-rev.4/webos-sdk-x86_64-armv7a-neon-toolchain-1.0.g.sh -P ${{github.workspace}}/temp

    - name: Install webOS NDK
      run: chmod 755 ${{github.workspace}}/temp/webos-sdk-x86_64-armv7a-neon-toolchain-1.0.g.sh && sudo ${{github.workspace}}/temp/webos-sdk-x86_64-armv7a-neon-toolchain-1.0.g.sh -y

    - name: Initialize NDK Environments
      run: env -i bash -c '. /opt/webos-sdk-x86_64/1.0.g/environment-setup-armv7a-neon-webos-linux-gnueabi && env' >> $GITHUB_ENV

    - name: CMake Version
      run: cmake --version

    - name: Create Build directory
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Build component
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DCMAKE_TOOLCHAIN_FILE=/opt/webos-sdk-x86_64/1.0.g/sysroots/x86_64-webossdk-linux/usr/share/cmake/OEToolchainConfig.cmake .. && make hyperion-webos gm_backend halgal_backend dile_vt_backend vtcapture_backend

    - name: List files
      run: find .

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: hyperion_webos_${{ matrix.build-type }}
        path: |
          ${{github.workspace}}/build/hyperion-webos
          ${{github.workspace}}/build/*.so
